import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
const runFile=promisify(execFile);
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const root=process.cwd();const dir=path.join(root,'.test-vscode');await fs.rm(path.join(dir,'user'),{recursive:true,force:true});await fs.mkdir(path.join(dir,'user','User'),{recursive:true});
await fs.writeFile(path.join(dir,'user','User','settings.json'),JSON.stringify({'workbench.startupEditor':'none','window.restoreWindows':'none','security.workspace.trust.enabled':false,'telemetry.telemetryLevel':'off','workbench.colorTheme':'Default Dark Modern','window.zoomLevel':0,'files.autoSave':'off','files.simpleDialog.enable':true}));
await Promise.all(['ready.json','finish','read-clipboard','clipboard.txt'].map(f=>fs.rm(path.join(dir,f),{force:true})));
await build({entryPoints:['test/vscode-suite.ts'],bundle:true,platform:'node',format:'cjs',external:['vscode'],outfile:'dist/vscode-tests.cjs'});
const executable=process.env.VSCODE_EXECUTABLE||'/Applications/Visual Studio Code.app/Contents/MacOS/Code';
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;delete env.NODE_OPTIONS;
const port=process.env.DIFF_STUDIO_DEBUG_PORT||'9333';const log=await fs.open('artifacts/vscode.log','w');
const extensionPath=process.env.DIFF_STUDIO_EXTENSION_PATH||root;
const child=spawn(executable,[`--extensionDevelopmentPath=${extensionPath}`,`--extensionTestsPath=${path.join(root,'dist/vscode-tests.cjs')}`,`--user-data-dir=${path.join(dir,'user')}`,`--extensions-dir=${path.join(dir,'extensions')}`,`--remote-debugging-port=${port}`,'--disable-workspace-trust','--skip-welcome','--skip-release-notes','--disable-updates','--new-window',root],{env,stdio:['ignore',log.fd,log.fd]});
let browser;const checks=[];const failures=[];const remoteFiles=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,timeout=60000){const start=Date.now();let error;while(Date.now()-start<timeout){try{const value=await fn();if(value)return value;}catch(e){error=e;}await wait(250);}throw error||new Error('Timed out');}
try{
 browser=await until(()=>chromium.connectOverCDP(`http://127.0.0.1:${port}`));
 const ready=await until(async()=>JSON.parse(await fs.readFile(path.join(dir,'ready.json'),'utf8')));
 const context=browser.contexts()[0];const page=await until(()=>context.pages().find(p=>p.url().includes('workbench')));
 page.on('pageerror',e=>failures.push(e.message));
 const frame=await until(async()=>{for(const f of page.frames()){if(await f.locator('#compare').count())return f;}return undefined;});
 await frame.locator('#comparison').waitFor({state:'visible'});await until(async()=>(await frame.locator('#stats').textContent()).includes('change'));
 const ensureSetup=async id=>{if(await frame.locator('#'+id).evaluate(el=>!!el.closest('#top-panel'))&&!(await frame.locator('#top-panel').isVisible())){await frame.locator('#top-toggle').click();await frame.locator('#top-panel').waitFor({state:'visible'});}};
 const click=async id=>{await ensureSetup(id);if(await frame.locator('#'+id).evaluate(el=>!!el.closest('#sidebar'))&&await frame.locator('body').evaluate(el=>el.classList.contains('sidebar-auto-hide'))){await frame.locator('#sidebar-handle').hover();await until(async()=>await frame.locator('#sidebar').evaluate(el=>getComputedStyle(el).opacity==='1'));}await frame.locator('#'+id).click();if(id==='compare')await until(async()=>!(await frame.locator('#top-panel').isVisible())||await frame.locator('#message.error').isVisible());};const fill=async(id,v)=>{await ensureSetup(id);await frame.locator('#'+id).fill(v);};const select=async(id,v)=>{await ensureSetup(id);await frame.locator('#'+id).selectOption(v);};
 const request=async(route,body,follow=true)=>{if(follow&&['/open','/project','/folders'].includes(route)){await frame.locator('#follow-agent').check();await until(async()=>await frame.locator('#follow-agent-control').getAttribute('data-follow')==='true');}const storage=path.dirname(ready.descriptor);const descriptorFile=(await fs.readdir(storage)).find(name=>name.endsWith('.bridge.json'));assert.ok(descriptorFile,'Agent bridge descriptor exists');const descriptor=JSON.parse(await fs.readFile(path.join(storage,descriptorFile),'utf8'));const r=await fetch(descriptor.url+route,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${descriptor.token}`},body:body?JSON.stringify(body):undefined});const json=await r.json();assert.equal(r.status,200,JSON.stringify(json));return json;};
 async function pickQuick(text){const dialog=page.locator('.quick-input-widget');await dialog.waitFor({state:'visible'});await dialog.locator('input').first().fill(text);await page.keyboard.press('Enter');}
 if(process.env.DIFF_STUDIO_ARCHIVE_REOPEN){
  const file=path.resolve(process.env.DIFF_STUDIO_ARCHIVE_REOPEN);const saved=JSON.parse(await fs.readFile(file,'utf8'));await click('import-session');const picker=page.locator('.quick-input-widget');await picker.waitFor({state:'visible'});await picker.locator('input').first().fill(file);await picker.getByRole('button',{name:/^(OK|Open)$/}).click();await page.locator('.quick-input-title').filter({hasText:/^Open session$/}).waitFor({state:'visible'});await picker.locator('input').first().fill('Review bundled snapshots');await page.keyboard.press('Enter');
  await until(async()=>(await frame.locator('#right-info').textContent()).includes('Archived snapshot'));await until(async()=>await frame.locator('#diff-editor .line-comment').count()===3);assert.ok((await frame.locator('#diff-editor .comment-body').allTextContents()).includes('Offline review annotation'));assert.ok(await frame.locator('#review-sessions button').count()>=saved.sessions.length);checks.push('A fresh extension process restores all snapshots and comments with every original fixture moved away');
  const index=saved.groups.findIndex(g=>g.entries.some(e=>e.path==='src/nested/tree.ts'));assert.ok(index>=0);await frame.locator('#review-groups button').nth(index).click();await frame.locator('[data-path="src/nested/tree.ts"]').click();await until(async()=>(await frame.locator('#right-info').textContent()).includes('Archived snapshot'));assert.ok((await frame.locator('#right-name').textContent()).endsWith('/src/nested/tree.ts'));checks.push('Saved changed-file groups and nested file navigation work without source files or Git');
  await click('link-repository');await picker.waitFor({state:'visible'});const title=await page.locator('.quick-input-title').textContent();if(title.includes('Which archived repository')){await page.keyboard.press('Enter');await page.locator('.quick-input-title').filter({hasText:'Locate matching local repository'}).waitFor({state:'visible'});}
  await picker.locator('input').first().fill(ready.fixtures.root+path.sep);await picker.getByRole('button',{name:'Link repository',exact:true}).click();await until(async()=>(await frame.locator('#message').textContent()).includes('archive remains fully available'));assert.equal(await frame.locator('#save-right').isDisabled(),true);checks.push('Link repository picker keeps archive snapshots intact when the selected folder is not a matching repository');
 }else{
 if(!process.env.DIFF_STUDIO_COMMENTS_ONLY){
 await select('mode','files');checks.push('VS Code activates; commands registered; real webview renders Monaco diff');
 const activityIcon=page.locator('.activitybar [aria-label^="Diff Studio"]').first();await activityIcon.click();await frame.locator('#compare').waitFor({state:'visible'});await page.locator('.sidebar').getByText('Open Comparison Studio',{exact:true}).click();checks.push('Activity Bar icon opens Diff Studio and its launcher command works');
 await click('settings-toggle');await frame.locator('#settings').waitFor({state:'visible'});
 for(const id of ['ignoreWhitespace','wordWrap','hideUnchanged']){await frame.locator('#setting-'+id).check();}
 await fill('setting-fontSize','15');await frame.locator('#setting-fontSize').press('Tab');
 await fill('setting-baseBranch','master');await frame.locator('#setting-baseBranch').press('Tab');
 await fill('setting-maxFileMB','12');await frame.locator('#setting-maxFileMB').press('Tab');
 await fill('setting-sshTimeoutSeconds','30');await frame.locator('#setting-sshTimeoutSeconds').press('Tab');
 await select('setting-layout','inline');await until(async()=>await frame.locator('#layout').inputValue()==='inline');await select('setting-layout','sideBySide');await click('settings-close');
 await until(async()=>{const s=JSON.parse(await fs.readFile(path.join(dir,'user','User','settings.json'),'utf8'));return s['diffStudio.fontSize']===15&&s['diffStudio.wordWrap']===true&&s['diffStudio.sshTimeoutSeconds']===30;});checks.push('Settings button; all eight settings persist to VS Code; close settings');
 await click('settings-shortcut');await frame.locator('#setting-sidebarAutoHide').check();await click('settings-close');await frame.locator('#panel-controls').hover();await until(async()=>!(await frame.locator('#sidebar').isVisible()));await frame.locator('#sidebar-handle').hover();await frame.locator('#sidebar').waitFor({state:'visible'});await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'hidden'});await frame.locator('#settings-shortcut').press('Tab');await frame.locator('#sidebar-handle').focus();await frame.locator('#sidebar').waitFor({state:'visible'});await click('settings-shortcut');await frame.locator('#setting-sidebarAutoHide').uncheck();await click('settings-close');checks.push('Auto-hide file list reveals on hover and keyboard focus, hides on leave, and can be disabled');
 await click('sidebar-handle');assert.equal(await frame.locator('#sidebar-handle').getAttribute('aria-pressed'),'true');await click('history-tab');await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'hidden'});await frame.locator('#sidebar-handle').hover();await click('files-tab');await frame.locator('#filter').click();await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'hidden'});await click('sidebar-handle');await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'visible'});await until(async()=>JSON.parse(await fs.readFile(path.join(dir,'user','User','settings.json'),'utf8'))['diffStudio.sidebarAutoHide']===false);checks.push('Hamburger toggles and persists auto-hide; clicking sidebar tabs or filter no longer prevents hiding on pointer leave');
 async function resizeSidebar(delta){const grip=await frame.locator('#sidebar-resizer').boundingBox();assert.ok(grip);await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();await page.mouse.move(grip.x+grip.width/2+delta,grip.y+grip.height/2,{steps:10});await page.mouse.up();}
 const sidebarWidth=async()=>Number(await frame.locator('#sidebar-resizer').getAttribute('aria-valuenow'));
 const initialWidth=await sidebarWidth();await resizeSidebar(110);assert.equal(await sidebarWidth(),initialWidth+110);await until(async()=>JSON.parse(await fs.readFile(path.join(dir,'user','User','settings.json'),'utf8'))['diffStudio.sidebarWidth']===initialWidth+110);await frame.locator('#sidebar-resizer').focus();await page.keyboard.press('ArrowLeft');assert.equal(await sidebarWidth(),initialWidth+100);checks.push('Dragging sidebar edge grows the file list and persists its width; keyboard separator also resizes');
 await click('sidebar-handle');await frame.locator('#sidebar-handle').hover();await resizeSidebar(40);assert.equal(await sidebarWidth(),initialWidth+140);await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'hidden'});await click('sidebar-handle');assert.ok(Math.abs((await frame.locator('#sidebar-rail').boundingBox()).width-(initialWidth+140))<2);await click('settings-shortcut');await fill('setting-sidebarWidth','260');await frame.locator('#setting-sidebarWidth').press('Tab');await click('settings-close');await until(async()=>await sidebarWidth()===260);checks.push('Auto-hide overlay stays open while dragging, hides after release and retains width when pinned; width setting applies');

 await click('top-toggle');await frame.locator('#top-panel').waitFor({state:'hidden'});await click('settings-shortcut');await frame.locator('#settings').waitFor({state:'visible'});await click('settings-close');await click('top-toggle');await frame.locator('#top-panel').waitFor({state:'visible'});await click('bottom-toggle');assert.equal(await frame.locator('#activity').isVisible(),false);assert.equal(await frame.locator('.editor-footer').isVisible(),false);await click('bottom-toggle');await frame.locator('#activity').waitFor({state:'visible'});checks.push('Top and bottom panels hide and restore; Settings remains accessible');
 await click('settings-shortcut');await frame.locator('#setting-showTopBar').uncheck();await frame.locator('#setting-showBottomBar').uncheck();await until(async()=>{const s=JSON.parse(await fs.readFile(path.join(dir,'user','User','settings.json'),'utf8'));return s['diffStudio.showTopBar']===false&&s['diffStudio.showBottomBar']===false;});await frame.locator('#setting-showTopBar').check();await frame.locator('#setting-showBottomBar').check();await click('settings-close');checks.push('Panel visibility settings persist to VS Code');
 for(const layout of ['inline','left','right','sideBySide']){await select('layout',layout);if(layout==='left'||layout==='right')await frame.locator('#focus-editor').waitFor({state:'visible'});else await frame.locator('#diff-editor').waitFor({state:'visible'});}checks.push('Inline, side-by-side, focus left/right layouts');
 await click('next');await click('previous');await select('language','python');checks.push('Previous/next change navigation and language selection');
 // Enter text through real editor keyboard input on both sides, then click their save buttons.
 for(const side of ['left','right']){await select('layout',side);const editor=frame.locator('#focus-editor .monaco-editor');await editor.click({position:{x:220,y:35}});await page.keyboard.press('Control+End');await page.keyboard.press('Meta+End');await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.type(`// UI ${side} edit`);await until(async()=>await frame.locator('#save-'+side).isEnabled());await click('save-'+side);await until(async()=>(await fs.readFile(path.join(ready.fixtures[side],'sample.ts'),'utf8')).includes(`UI ${side} edit`));}
 checks.push('Real keyboard edits and Save left / Save right persist both files');
 await select('layout','sideBySide');const originalLeft=await frame.locator('#left-name').textContent();await click('swap');await until(async()=>await frame.locator('#right-name').textContent()===originalLeft);await click('swap');await click('reload');checks.push('Swap sources and reload');
 await click('activity-toggle');assert.equal(await frame.locator('#activity-list').isVisible(),false);await click('activity-toggle');checks.push('Activity collapse and expand');
 await select('mode','directories');await fill('left-path',ready.fixtures.left);await fill('right-path',ready.fixtures.right);await click('compare');await until(async()=>Number(await frame.locator('#file-count').textContent())===3);await fill('filter','sample');assert.equal(await frame.locator('#changes button').count(),1);await frame.locator('#changes button').first().click();await fill('filter','');checks.push('Folder comparison, file filter and changed-file selection');await frame.locator('#top-panel').waitFor({state:'hidden'});assert.equal(await frame.locator('#top-toggle').textContent(),'Choose files / revisions');assert.equal(await frame.locator('#agent').isVisible(),true);assert.equal(await frame.locator('#copy-agent').isVisible(),true);await click('top-toggle');assert.equal(await frame.locator('#top-toggle').textContent(),'Collapse comparison setup');assert.equal(await frame.locator('#left-path').inputValue(),ready.fixtures.left);checks.push('Successful Open comparison collapses setup while preserving inputs and keeping agent controls accessible; descriptive toggle restores it');
 await select('mode','gitRevisions');await fill('repo',ready.fixtures.repo);await fill('git-file','app.ts');await fill('left-ref','master');await fill('right-ref','HEAD');await click('compare');await until(async()=>await frame.locator('#right-info').textContent().then(t=>t.includes('Read only')));assert.equal(await frame.locator('#save-left').isDisabled(),true);assert.equal(await frame.locator('#save-right').isDisabled(),true);checks.push('Two Git revisions render as read-only');
 await click('refresh-versions');await until(async()=>(await frame.locator('#left-version optgroup[label^="Commits"] option').count())===2);
 let commits=await frame.locator('#left-version optgroup[label^="Commits"] option').evaluateAll(options=>options.map(o=>({value:o.value,label:o.textContent})));assert.equal(commits[0].value,ready.fixtures.head);assert.match(commits[0].label,/2024/);assert.ok(await frame.locator('#left-version option[value="refs/tags/v1.0"]').count());await select('revision-order','oldest');assert.equal(await frame.locator('#left-version optgroup[label^="Commits"] option').first().getAttribute('value'),ready.fixtures.base);await select('revision-order','newest');
 await select('left-version',ready.fixtures.base);await select('right-version',ready.fixtures.head);assert.equal(await frame.locator('#left-ref').inputValue(),ready.fixtures.base);assert.equal(await frame.locator('#right-ref').inputValue(),ready.fixtures.head);await click('compare');await until(async()=>(await frame.locator('#right-name').textContent()).includes(ready.fixtures.head.slice(0,24)));checks.push('Left/right revision dropdowns show dated commits, branches and tags, sort both ways and open selected versions');
 await select('right-version','WORKING');assert.equal(await frame.locator('#mode').inputValue(),'gitWorking');await click('compare');await until(async()=>(await frame.locator('#right-info').textContent()).includes('Editable'));await select('right-version',ready.fixtures.head);assert.equal(await frame.locator('#mode').inputValue(),'gitRevisions');checks.push('Right version selector switches between working file and Git revision');
 await click('browse-repo-file');await page.locator('.quick-input-widget').waitFor({state:'visible'});await page.locator('.quick-input-widget input').first().fill('app.ts');await page.keyboard.press('Enter');await page.locator('.quick-input-widget').waitFor({state:'hidden'});await until(async()=>await frame.locator('#git-file').inputValue()==='app.ts'&&(await frame.locator('#right-name').textContent()).includes(ready.fixtures.head.slice(0,24)));checks.push('Repository-relative file picker selects a file from the chosen versions');
 await click('history');await page.locator('.quick-input-widget').waitFor({state:'visible'});await page.keyboard.press('Enter');await page.locator('.quick-input-widget').waitFor({state:'hidden'});await until(async()=>await frame.locator('#left-ref').inputValue()===ready.fixtures.head);checks.push('History picker selects real commit');
 await select('mode','gitWorking');await fill('left-ref','HEAD');await click('compare');await until(async()=>await frame.locator('#right-info').textContent().then(t=>t.includes('Editable'))&&(await frame.locator('#right-name').textContent())===path.join(ready.fixtures.repo,'app.ts'));checks.push('Git working comparison keeps current pane editable');
 await fill('git-file',path.join(ready.fixtures.repo,'app.ts'));await click('compare');await until(async()=>await frame.locator('#git-file').inputValue()==='app.ts'&&(await frame.locator('#right-name').textContent())===path.join(ready.fixtures.repo,'app.ts'));checks.push('Absolute Git file path normalizes and opens the correct working file');
 await fill('git-file','');await click('compare');await until(async()=>(await frame.locator('#message').textContent()).includes('Repository · HEAD ↔ working tree'));assert.ok(Number(await frame.locator('#file-count').textContent())>=3);await fill('git-file',ready.fixtures.repo);await click('compare');await until(async()=>await frame.locator('#git-file').inputValue()==='');checks.push('Blank path and full repository folder open Git changed-file lists');
 await select('mode','gitRevisions');await fill('left-ref','HEAD');await fill('right-ref','master');await click('compare');await until(async()=>(await frame.locator('#message').textContent()).includes('HEAD ↔ master'));assert.equal(Number(await frame.locator('#file-count').textContent()),4);checks.push('Git folder comparison respects the selected right-hand revision');
 await select('mode','gitWorking');
 async function chooseGitPath(id,location,directory){
  await click(id);const dialog=page.locator('.quick-input-widget');await dialog.waitFor({state:'visible'});const box=dialog.locator('input').first();await box.fill(location+(directory?path.sep:''));
  if(directory){await dialog.getByRole('button',{name:'Select folder',exact:true}).click();}else await box.press('Enter');
  await dialog.waitFor({state:'hidden'});await until(async()=>await frame.locator('#compare').isEnabled());
 }
 await chooseGitPath('browse-git-file',path.join(ready.fixtures.repo,'app.ts'),false);await until(async()=>await frame.locator('#git-file').inputValue()==='app.ts');checks.push('Git Browse file accepts an actual file selection and opens the diff');
 await chooseGitPath('browse-git-folder',ready.fixtures.repo,true);await until(async()=>await frame.locator('#git-file').inputValue()==='');checks.push('Git Browse folder accepts an actual folder selection and lists changes');
 await chooseGitPath('browse-repo',ready.fixtures.repo,true);await until(async()=>(await frame.locator('#message').textContent()).includes('Repository · HEAD'));checks.push('Repository Browse opens folder changes without requiring a file path');
 await select('mode','gitBase');await fill('left-ref','master');await click('compare');await until(async()=>Number(await frame.locator('#file-count').textContent())>=5);await ensureSetup('merge-base');await frame.locator('#merge-base').check();await select('git-mode','committed');await click('compare');await until(async()=>Number(await frame.locator('#file-count').textContent())===4);await fill('left-ref','HEAD');await select('git-mode','staged');await click('compare');await until(async()=>Number(await frame.locator('#file-count').textContent())===1);checks.push('Base branch diff: working, committed, staged, common ancestor');
 await click('refresh-versions');await until(async()=>await frame.locator('#left-version option[value="refs/heads/master"]').count());await select('left-version','refs/heads/master');await select('git-mode','working');await click('compare');await until(async()=>Number(await frame.locator('#file-count').textContent())>=5);assert.equal(await frame.locator('#left-version option[value="INDEX"]').count(),0);checks.push('Changes against branch has a populated branch/tag/commit dropdown');
 let sessions=await request('/sessions');let s=sessions.find(s=>s.right.writable&&s.right.source.uri?.endsWith('/app.ts'));
 await request('/reveal',{id:s.id});await request('/note',{id:s.id,message:'Agent: add a visible marker to explain this edit.'});await request('/edit',{id:s.id,side:'right',text:s.right.text+'// agent visual change\n',expectedHash:s.right.hash});await until(async()=>(await frame.locator('#activity-list').textContent()).includes('Agent: add'));await request('/save',{id:s.id,side:'right'});assert.match(await fs.readFile(path.join(ready.fixtures.repo,'app.ts'),'utf8'),/agent visual change/);checks.push('Authenticated agent opens/reveals, narrates, edits and saves in the real UI');
 const bomFile=path.join(ready.fixtures.root,'unicode-bom.ts');await fs.writeFile(bomFile,'\ufeff// 你好 😀\r\nconst n = 1;\r\n');
 const bom=await request('/open',{left:{kind:'text',text:'\ufeff// 你好 😀\r\nconst n = 1;\r\n',label:'Original.ts'},right:{kind:'file',uri:bomFile}});
 await until(async()=>(await frame.locator('#right-name').textContent())===bomFile);assert.equal(await frame.locator('#save-right').isDisabled(),true);
 await select('layout','right');await frame.locator('#focus-editor .monaco-editor').click({position:{x:240,y:32}});await page.keyboard.press('Meta+End');await page.keyboard.press('End');await page.keyboard.type('// preserved');await until(async()=>await frame.locator('#save-right').isEnabled());await click('save-right');await until(async()=>(await fs.readFile(bomFile,'utf8')).includes('preserved'));const bomText=await fs.readFile(bomFile,'utf8');assert.ok(bomText.startsWith('\ufeff'));assert.ok(bomText.includes('\r\n'));checks.push('Real editor preserves UTF-8 BOM, Unicode and CRLF through edits and save');
 if(process.env.DIFF_STUDIO_REMOTE_UI){
  const host=process.env.DIFF_STUDIO_REMOTE_UI;const stamp=Date.now();remoteFiles.push(`/tmp/diff-studio-ui-${stamp}-left.ts`,`/tmp/diff-studio-ui-${stamp}-right.ts`);const uris=remoteFiles.map(p=>`ssh://${host}${p}`);
  console.log('Testing live remote files in the VS Code UI…');
  let remote=await request('/open',{title:'Live SSH comparison',left:{kind:'file',uri:uris[0],allowMissing:true},right:{kind:'file',uri:uris[1],allowMissing:true}});
  await select('layout','sideBySide');
  for(const side of ['left','right']){remote=await request('/edit',{id:remote.id,side,text:`// remote UI ${side} saved\nexport const n = ${side==='left'?1:2};\n`,expectedHash:remote[side].hash,message:`Agent: update the remote ${side} file.`});await until(async()=>await frame.locator('#save-'+side).isEnabled());await click('save-'+side);await until(async()=>!(await request('/sessions')).find(s=>s.id===remote.id)[side].dirty);}
  const readback=await request('/open',{title:'SSH readback',left:{kind:'file',uri:uris[0]},right:{kind:'file',uri:uris[1]}});assert.match(readback.left.text,/remote UI left saved/);assert.match(readback.right.text,/remote UI right saved/);await until(async()=>(await frame.locator('#right-name').textContent())===uris[1]);await page.screenshot({path:'artifacts/vscode-remote.png',fullPage:true});
  await select('mode','files');await fill('left-path',path.join(ready.fixtures.left,'sample.ts'));await fill('right-path',uris[1]);await click('compare');await until(async()=>(await frame.locator('#left-name').textContent())===path.join(ready.fixtures.left,'sample.ts'));checks.push(`Live SSH UI on ${host}: remote/remote both save buttons, readback, local/remote comparison`);
 }
 await click('history-tab');await frame.locator('#sessions .session-item').first().click();checks.push('History tab reopens a recent comparison');
 await click('native');await page.locator('.monaco-diff-editor').first().waitFor({state:'visible'});await page.locator('.tab').filter({hasText:'Diff Studio'}).first().click();await frame.locator('#comparison').waitFor({state:'visible'});checks.push('Native editor opens a VS Code diff');
 // Native OS Browse dialogs are invoked and cancelled; they never mutate fixtures.
 await select('mode','files');for(const id of ['browse-left','browse-right']){await click(id);await wait(800);await page.keyboard.press('Escape');}await select('mode','gitWorking');await click('browse-repo');await wait(800);await page.keyboard.press('Escape');checks.push('Browse left/right/repository buttons invoke selectors (cancel path)');
 await click('agent');await until(async()=>(await frame.locator('#bridge-status').textContent())==='Agent offline');await click('agent');await until(async()=>(await frame.locator('#bridge-status').textContent())==='Agent bridge ready');checks.push('Agent disconnect/connect buttons');
 assert.equal(await frame.locator('#copy-agent').isVisible(),true);assert.ok(!(await frame.locator('#message').textContent()).includes('Agent ready. Descriptor'));
 await click('copy-agent');await until(async()=>(await frame.locator('#copy-agent').textContent())==='Instructions copied');await fs.writeFile(path.join(dir,'read-clipboard'),'read');const handoff=await until(async()=>await fs.readFile(path.join(dir,'clipboard.txt'),'utf8'));
 const start=handoff.indexOf('\n{')+1;const end=handoff.indexOf('\n}\n',start)+2;const connection=JSON.parse(handoff.slice(start,end));assert.ok(connection.cli.startsWith(extensionPath));assert.ok(connection.skillPath.startsWith(extensionPath));assert.ok(handoff.includes((await fs.readFile(connection.skillPath,'utf8')).trim()));assert.ok(!handoff.includes(JSON.parse(await fs.readFile(connection.descriptor,'utf8')).token));
 const startup=handoff.split('\n').find(line=>line.startsWith('node '));assert.ok(JSON.parse((await runFile('/bin/sh',['-c',startup])).stdout).length>0);
 const cli=async(...args)=>JSON.parse((await runFile(process.execPath,[connection.cli,'--bridge',connection.descriptor,...args])).stdout);
 const handoffTarget=path.join(ready.fixtures.root,'handoff.ts');const proposed=path.join(ready.fixtures.root,'handoff-proposed.ts');const requestPath=path.join(ready.fixtures.root,'handoff-request.json');await fs.writeFile(handoffTarget,'const value = 1;\n');await fs.writeFile(proposed,'const value = 2;\n');await fs.writeFile(requestPath,JSON.stringify({title:'Fresh session handoff',left:{kind:'text',label:'Before agent changes',text:'const value = 1;\n'},right:{kind:'file',uri:handoffTarget}}));
 const opened=await cli('request',requestPath);await cli('note',opened.id,'Explain a visible change from a fresh process');await cli('edit',opened.id,'right',proposed,'Increase the value');await until(async()=>(await frame.locator('#right-name').textContent())===handoffTarget&&await frame.locator('#save-right').isEnabled());assert.equal(await fs.readFile(handoffTarget,'utf8'),'const value = 1;\n');await cli('comment',opened.id,'right','1','Handoff line comment');await until(async()=>(await frame.locator('.comment-body').allTextContents()).includes('Handoff line comment'));await cli('save',opened.id,'right');assert.equal(await fs.readFile(handoffTarget,'utf8'),'const value = 2;\n');checks.push('Copy agent instructions contains packaged skill and live context; fresh CLI processes list, open, explain, preview, comment and save visible changes without embedding credentials');
 await click('agent');await until(async()=>(await frame.locator('#bridge-status').textContent())==='Agent offline');assert.equal(await frame.locator('#copy-agent').isVisible(),false);assert.ok(!(await frame.locator('#message').textContent()).includes('Agent ready. Descriptor'));await assert.rejects(fs.stat(connection.descriptor));await click('agent');await frame.locator('#copy-agent').waitFor({state:'visible'});checks.push('Disconnect removes copy action and invalidates old handoff without leaving a connection banner');

 await select('mode','files');await fill('left-path','/nonexistent/diff-studio-file');await fill('right-path',path.join(ready.fixtures.right,'sample.ts'));await click('compare');await frame.locator('#message.error').waitFor();assert.match(await frame.locator('#message').textContent(),/does not exist/);assert.equal(await frame.locator('#compare').isEnabled(),true);assert.equal(await frame.locator('#top-panel').isVisible(),true);checks.push('Failed comparison keeps setup visible for correction; compare button recovers');
 await fill('left-path',path.join(ready.fixtures.left,'sample.ts'));await click('compare');await until(async()=>!(await frame.locator('#message').isVisible()));await select('layout','sideBySide');
 // New history and Explorer behavior.
 await click('settings-shortcut');await fill('setting-comparisonHistoryLimit','2');await frame.locator('#setting-comparisonHistoryLimit').press('Tab');await fill('setting-remoteHistoryLimit','2');await frame.locator('#setting-remoteHistoryLimit').press('Tab');await click('settings-close');
 await click('history-tab');const historyPaths=[];let latest;
 for(let i=1;i<=3;i++){const uri=path.join(ready.fixtures.root,`recent-${i}.ts`);historyPaths.push(uri);await fs.writeFile(uri,`const n = ${i};\n`);latest=await request('/open',{left:{kind:'file',uri:path.join(ready.fixtures.left,'sample.ts')},right:{kind:'file',uri},title:`Recent comparison ${i}`});await until(async()=>(await frame.locator('#sessions .session-item').first().textContent()).includes(`Recent comparison ${i}`));}
 assert.equal(await frame.locator('#sessions .session-item').count(),2);assert.equal(await frame.locator('#sessions').getByText('Recent comparison 1',{exact:true}).count(),0);
 await frame.locator('#sessions .session-item').last().click();await until(async()=>(await frame.locator('#right-name').textContent())===historyPaths[1]);await until(async()=>(await frame.locator('#sessions .session-item').first().textContent()).includes('Recent comparison 2'));assert.equal(await frame.locator('#sessions .session-item').count(),2);checks.push('Recent comparisons obey the configured limit, deduplicate, reopen and move to the front');
 await frame.locator('#sessions .history-remove').first().click();await until(async()=>(await frame.locator('#sessions .session-item').count())===1);assert.equal(await frame.locator('#right-name').textContent(),historyPaths[1]);await page.screenshot({path:'artifacts/v030-history.png',fullPage:true});checks.push('History rows have an independent remove button that leaves the current editor open');
 await request('/edit',{id:latest.id,side:'right',text:latest.right.text+'// unsaved history test\n',expectedHash:latest.right.hash});await click('settings-shortcut');await fill('setting-comparisonHistoryLimit','0');await frame.locator('#setting-comparisonHistoryLimit').press('Tab');await click('settings-close');await until(async()=>(await frame.locator('#sessions .session-item').count())===0);await frame.locator('#unsaved .session-item').filter({hasText:'Recent comparison 3'}).click();await until(async()=>(await frame.locator('#right-name').textContent())===historyPaths[2]);assert.equal(await frame.locator('#save-right').isEnabled(),true);await click('save-right');await until(async()=>!(await frame.locator('#save-right').isEnabled()));checks.push('Disabling history clears recents without discarding unsaved buffers; buffers remain selectable and savable');
 await click('settings-shortcut');await fill('setting-comparisonHistoryLimit','10');await frame.locator('#setting-comparisonHistoryLimit').press('Tab');await click('settings-close');
 const nested=path.join(ready.fixtures.right,'src','nested');await fs.mkdir(nested,{recursive:true});await fs.writeFile(path.join(nested,'tree.ts'),'export const tree = true;\n');await select('mode','directories');await fill('left-path',ready.fixtures.left);await fill('right-path',ready.fixtures.right);await click('compare');await until(async()=>(await frame.locator('#file-count').textContent())==='4');assert.equal(await frame.locator('#files-tab').getAttribute('aria-selected'),'true');const folder=frame.locator('#changes summary').filter({hasText:/^src$/});await folder.click();await frame.locator('[data-path="src/nested/tree.ts"]').waitFor({state:'hidden'});await folder.focus();await page.keyboard.press('ArrowRight');await frame.locator('[data-path="src/nested/tree.ts"]').waitFor({state:'visible'});await fill('filter','tree.ts');assert.equal(await frame.locator('#changes .change-item').count(),1);await frame.locator('#changes .change-item').click();await until(async()=>(await frame.locator('#right-name').textContent()).endsWith('/src/nested/tree.ts'));await fill('filter','');await page.screenshot({path:'artifacts/v030-tree.png',fullPage:true});checks.push('Files tab renders a nested Explorer tree with collapse, keyboard expand, filtering and file opening');
 const indents=await frame.locator('.change-folder > [role=group]').evaluateAll(groups=>groups.map(group=>{const css=getComputedStyle(group);return parseFloat(css.paddingLeft)+parseFloat(css.marginLeft)+parseFloat(css.borderLeftWidth);}));assert.ok(indents.length>=2&&indents.every(indent=>indent<=6));await click('sidebar-handle');await frame.locator('#sidebar-handle').hover();await frame.locator('[data-path="src/nested/tree.ts"]').click();await frame.locator('#panel-controls').hover();await frame.locator('#sidebar').waitFor({state:'hidden'});await click('sidebar-handle');checks.push('Nested tree uses only six pixels per level; opening a changed file does not hold auto-hide open');

 await click('history-tab');assert.equal(await frame.locator('#files-panel').isVisible(),false);await page.keyboard.press('Home');await frame.locator('#files-panel').waitFor({state:'visible'});checks.push('Files and History are separate keyboard-accessible tabs');
 // SSH transport is exercised with the production Python payload against local fixtures.
 async function connectFixture(button,host,field){await page.locator('.quick-input-widget').waitFor({state:'hidden'});await click(button);await page.locator('.quick-input-title').filter({hasText:'Choose connection'}).waitFor({state:'visible'});await pickQuick('Connect to SSH VM');await page.locator('.quick-input-title').filter({hasText:'Connect to SSH VM'}).waitFor({state:'visible'});await pickQuick(host);await until(async()=>(await frame.locator('#'+field).inputValue()).includes(host));}
 async function remoteFolder(location){await pickQuick('Go to path');await page.locator('.quick-input-title').filter({hasText:'Go to remote folder'}).waitFor({state:'visible'});await pickQuick(location);await page.locator('.quick-input-title').filter({hasText:'Remote folder'}).waitFor({state:'visible'});}
 await select('mode','gitWorking');await fill('git-file','');await fill('left-ref','HEAD');await connectFixture('connect-repo','first.diff-studio.invalid','repo');await click('browse-repo');await remoteFolder(ready.fixtures.repo);await pickQuick('Select this folder');await until(async()=>(await frame.locator('#message').textContent()).includes('Repository · HEAD'));assert.ok((await frame.locator('#repo').inputValue()).startsWith('ssh://first.diff-studio.invalid/'));await click('browse-repo-file');await pickQuick('app.ts');await until(async()=>(await frame.locator('#right-name').textContent()).startsWith('ssh://first.diff-studio.invalid/')&&(await frame.locator('#right-name').textContent()).endsWith('/app.ts'));assert.ok((await frame.locator('#right-info').textContent()).includes('Editable'));checks.push('SSH connection button, remote folder navigation, repository selection and remote Git file comparison (fixture transport)');
 await connectFixture('connect-repo','second.diff-studio.invalid','repo');await connectFixture('connect-repo','third.diff-studio.invalid','repo');await click('connect-repo');let dialog=page.locator('.quick-input-widget');await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByText('first.diff-studio.invalid',{exact:true}).count(),0);assert.equal(await dialog.getByText('third.diff-studio.invalid',{exact:true}).count(),1);await dialog.getByText('second.diff-studio.invalid',{exact:true}).hover();await dialog.getByRole('button',{name:'Remove VM from history'}).first().click();await until(async()=>await dialog.getByText('second.diff-studio.invalid',{exact:true}).count()===0);await pickQuick('third.diff-studio.invalid');await until(async()=>(await frame.locator('#repo').inputValue()).includes('third.diff-studio.invalid'));checks.push('Recent VMs respect their configured limit, reconnect, and support removal');
 await dialog.waitFor({state:'hidden'});await click('connect-repo');await page.locator('.quick-input-title').filter({hasText:'Choose connection'}).waitFor({state:'visible'});await pickQuick('Connect to SSH VM');await page.locator('.quick-input-title').filter({hasText:'Connect to SSH VM'}).waitFor({state:'visible'});await pickQuick('offline.diff-studio.invalid');await until(async()=>(await frame.locator('#message.error').textContent()).includes('offline'));assert.ok((await frame.locator('#repo').inputValue()).includes('third.diff-studio.invalid'));await click('connect-repo');await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByText('offline.diff-studio.invalid',{exact:true}).count(),0);await pickQuick('Local computer');await until(async()=>(await frame.locator('#repo').inputValue())===root);await dialog.waitFor({state:'hidden'});checks.push('Failed SSH connections report an error without replacing the current target or entering history; local connection restores browsing');
 await select('mode','files');await connectFixture('connect-right','third.diff-studio.invalid','right-path');await click('browse-right');await pickQuick('right');await page.locator('.quick-input-title').filter({hasText:'Remote file'}).waitFor({state:'visible'});await pickQuick('sample.ts');await until(async()=>(await frame.locator('#right-path').inputValue()).endsWith('/right/sample.ts'));await fill('left-path',path.join(ready.fixtures.left,'sample.ts'));await click('compare');await until(async()=>(await frame.locator('#right-name').textContent()).endsWith('/right/sample.ts'));checks.push('Source SSH button browses remote files for a local-to-remote comparison (fixture transport)');
 if(process.env.DIFF_STUDIO_REMOTE_UI){await connectFixture('connect-right',process.env.DIFF_STUDIO_REMOTE_UI,'right-path');await click('browse-right');await pickQuick('Go to path');await page.locator('.quick-input-title').filter({hasText:'Go to remote folder'}).waitFor({state:'visible'});await pickQuick('/tmp');await page.locator('.quick-input-title').filter({hasText:'Remote file'}).waitFor({state:'visible'});await pickQuick(path.basename(remoteFiles[1]));await until(async()=>(await frame.locator('#right-path').inputValue()).endsWith(remoteFiles[1]));await click('compare');await until(async()=>(await frame.locator('#right-name').textContent()).endsWith(remoteFiles[1]));checks.push('Live Oracle VM connection picker navigates /tmp, selects a remote file and opens an editable comparison');}
 }else{
 const nested=path.join(ready.fixtures.right,'src','nested');await fs.mkdir(nested,{recursive:true});await fs.writeFile(path.join(nested,'tree.ts'),'export const tree = true;\n');await select('mode','directories');await fill('left-path',ready.fixtures.left);await fill('right-path',ready.fixtures.right);await click('compare');await until(async()=>(await frame.locator('#file-count').textContent())==='4');await request('/open',{left:{kind:'git',repo:ready.fixtures.repo,path:'app.ts',ref:'HEAD'},right:{kind:'file',uri:path.join(ready.fixtures.repo,'app.ts')}});
 }
 const portablePath=path.join(ready.fixtures.root,'portable-comment.ts');await fs.writeFile(portablePath,'first\nsecond\nthird\n');const portable=await request('/open',{title:'Portable comments demo',left:{kind:'text',label:'Original.ts',text:'first\nold second\nthird\n'},right:{kind:'file',uri:portablePath}});await until(async()=>(await frame.locator('#right-name').textContent())===portablePath);
 for(const [side,line,body] of [['left',1,'Explain the original <line>'],['right',2,'Review the new second line']]){
  await select('layout',side);const number=frame.locator('#focus-editor .line-numbers').filter({hasText:new RegExp('^'+line+'$')}).first();await number.hover();await frame.locator('#focus-editor .comment-add-glyph').first().waitFor({state:'visible'});await frame.locator('#focus-editor .comment-add-glyph').first().click();await frame.locator('.comment-input:visible').fill(body);await frame.locator('.comment-submit:visible').click();await until(async()=>(await frame.locator('#focus-editor .comment-body').allTextContents()).includes(body));
 }
 checks.push('Hovering the line gutter on either side adds a colored comment between code lines');
 await frame.locator('#focus-editor .comment-header button').filter({hasText:'Edit'}).click();await frame.locator('.comment-input:visible').fill('Updated review comment');await frame.locator('.comment-submit:visible').click();await until(async()=>(await frame.locator('#focus-editor .comment-body').allTextContents()).includes('Updated review comment'));
 await click('add-comment');await frame.locator('.comment-input:visible').fill('Temporary comment');await frame.locator('.comment-submit:visible').click();const temporary=frame.locator('#focus-editor .line-comment').filter({hasText:'Temporary comment'});await temporary.getByRole('button',{name:'Delete comment'}).click();await temporary.waitFor({state:'detached'});checks.push('Comment toolbar, editing and deletion work without changing file contents');
 let portableState=(await request('/sessions')).find(s=>s.id===portable.id);await request('/edit',{id:portable.id,side:'right',text:'inserted before\n'+portableState.right.text,expectedHash:portableState.right.hash});await until(async()=>(await frame.locator('#focus-editor .comment-header strong').textContent()).includes('line 3'));await select('layout','sideBySide');await until(async()=>await frame.locator('#diff-editor .line-comment').count()===2);await select('layout','inline');await until(async()=>await frame.locator('#diff-editor .modified .line-comment').count()===2);await select('layout','sideBySide');checks.push('Comments follow line insertions and remain visible in inline, side-by-side and focused layouts');
 const archiveFile=path.join(root,'artifacts','v040-review.diff_studio');const archiveUpdated=path.join(root,'artifacts','v040-review-updated.diff_studio');await fs.rm(archiveFile,{force:true});await fs.rm(archiveUpdated,{force:true});
 let previousSaveFile;
 async function saveSessionFile(file){await click('export-session');const picker=page.locator('.quick-input-widget');await picker.waitFor({state:'visible'});if(previousSaveFile)await until(async()=>await picker.locator('input').first().inputValue()===previousSaveFile);await picker.locator('input').first().fill(file);await picker.getByRole('button',{name:/^(OK|Save session)$/}).click();await until(async()=>{try{return (await fs.stat(file)).size>0;}catch{return false;}});previousSaveFile=file;}
 async function openSessionFile(file){await click('import-session');const picker=page.locator('.quick-input-widget');await picker.waitFor({state:'visible'});await picker.locator('input').first().fill(file);await picker.getByRole('button',{name:/^(OK|Open)$/}).click();await page.locator('.quick-input-title').filter({hasText:/^Open session$/}).waitFor({state:'visible'});await pickQuick('Review bundled snapshots');}
 await saveSessionFile(archiveFile);const savedArchive=JSON.parse(await fs.readFile(archiveFile,'utf8'));assert.equal(savedArchive.format,'diff-studio/session');const savedPortable=savedArchive.sessions.find(s=>s.id===portable.id);assert.equal(savedPortable.comments.length,2);assert.ok(savedPortable.right.text.startsWith('inserted before'));assert.equal(savedPortable.right.savedText,'first\nsecond\nthird\n');assert.ok(savedArchive.groups.some(g=>g.entries.some(e=>e.path==='src/nested/tree.ts')));checks.push('Save session writes .diff_studio with all compared file snapshots, unclicked tree entries, comments and unsaved edits');
 await fs.rename(portablePath,portablePath+'.moved');await openSessionFile(archiveFile);await until(async()=>await frame.locator('#review-tab').getAttribute('aria-selected')==='true');await until(async()=>(await frame.locator('#right-info').textContent()).includes('Archived snapshot'));assert.equal(await frame.locator('#save-right').isDisabled(),true);await until(async()=>await frame.locator('#diff-editor .line-comment').count()===2);assert.ok((await frame.locator('#diff-editor .comment-body').allTextContents()).includes('Updated review comment'));assert.ok((await frame.locator('#review-sessions button').count())>=savedArchive.sessions.length);checks.push('Open session restores every comparison and both-side comments after an original file is removed, without a repository');
 await select('layout','right');await click('add-comment');await frame.locator('.comment-input:visible').fill('Offline review annotation');await frame.locator('.comment-submit:visible').click();await until(async()=>(await frame.locator('#focus-editor .comment-body').allTextContents()).includes('Offline review annotation'));await saveSessionFile(archiveUpdated);const updated=JSON.parse(await fs.readFile(archiveUpdated,'utf8'));assert.ok(updated.sessions.some(s=>s.comments.some(c=>c.body==='Offline review annotation')));await page.screenshot({path:'artifacts/v040-comments.png',fullPage:true});checks.push('Detached archive supports new comments and saving another portable session');
 const invalidFile=path.join(ready.fixtures.root,'invalid.diff_studio');await fs.writeFile(invalidFile,JSON.stringify({format:'diff-studio/session',version:99}));await click('import-session');await page.locator('.quick-input-widget').waitFor({state:'visible'});await page.locator('.quick-input-widget input').first().fill(invalidFile);await page.locator('.quick-input-widget').getByRole('button',{name:/^(OK|Open)$/}).click();await until(async()=>(await frame.locator('#message.error').textContent()).includes('Unsupported'));assert.ok((await frame.locator('#focus-editor .comment-body').allTextContents()).includes('Offline review annotation'));checks.push('Unsupported archives report a clear error and leave the current review intact');
 const mixedRepo=path.join(ready.fixtures.root,'mixed-repo');await fs.mkdir(mixedRepo);const gitMixed=(...args)=>runFile('git',args,{cwd:mixedRepo});await gitMixed('init','-b','master');await gitMixed('config','user.name','Diff Test');await gitMixed('config','user.email','diff@example.invalid');await fs.writeFile(path.join(mixedRepo,'good.ts'),'const n = 1;\n');await fs.writeFile(path.join(mixedRepo,'asset.bin'),Buffer.from([0,1]));await gitMixed('add','.');await gitMixed('commit','-m','Before');await gitMixed('checkout','-b','feature');await fs.writeFile(path.join(mixedRepo,'good.ts'),'const n = 2;\n');await fs.writeFile(path.join(mixedRepo,'asset.bin'),Buffer.from([0,2]));await gitMixed('add','.');await gitMixed('commit','-m','After');
 for(const mode of ['gitRevisions','gitWorking','gitBase']){await select('mode',mode);await fill('repo',mixedRepo);if(mode!=='gitBase')await fill('git-file','');await fill('left-ref','master');if(mode==='gitRevisions')await fill('right-ref','HEAD');if(mode==='gitBase')await select('git-mode','working');await click('compare');await until(async()=>await frame.locator('#file-count').textContent()==='2');assert.equal(await frame.locator('#changes .unavailable').count(),1);await frame.locator('[data-path="good.ts"]').click();await until(async()=>(await frame.locator('#title').textContent())==='good.ts');const rightName=await frame.locator('#right-name').textContent();await frame.locator('[data-path="asset.bin"]').click();await until(async()=>(await frame.locator('#message.error').textContent()).includes('Binary'));assert.equal(await frame.locator('#title').textContent(),'good.ts');assert.equal(await frame.locator('#right-name').textContent(),rightName);await frame.locator('[data-path="good.ts"]').click();await until(async()=>await frame.locator('#compare').isEnabled());}
 checks.push('Revision/revision, revision/working and branch trees retain binary entries while opening text files; binary clicks show an explanation and preserve the current diff');
 const mixedLeft=path.join(ready.fixtures.root,'mixed-left'),mixedRight=path.join(ready.fixtures.root,'mixed-right');for(const folder of [mixedLeft,mixedRight]){await fs.mkdir(folder);await fs.writeFile(path.join(folder,'good.ts'),folder===mixedLeft?'before\n':'after\n');await fs.writeFile(path.join(folder,'asset.bin'),Buffer.from([0,folder===mixedLeft?1:2]));}await select('mode','directories');await fill('left-path',mixedLeft);await fill('right-path',mixedRight);await click('compare');assert.equal(await frame.locator('#changes .unavailable').count(),1);await frame.locator('[data-path="good.ts"]').click();await until(async()=>(await frame.locator('#right-name').textContent())===path.join(mixedRight,'good.ts'));assert.ok((await frame.locator('#right-info').textContent()).includes('Editable'));checks.push('Mixed folder comparison keeps supported text editable and marks only the binary file unavailable');
 const mixedArchive=path.join(root,'artifacts','v043-mixed.diff_studio');await fs.rm(mixedArchive,{force:true});await saveSessionFile(mixedArchive);const archived=JSON.parse(await fs.readFile(mixedArchive,'utf8'));assert.ok(archived.groups.some(g=>g.entries.some(e=>e.path==='asset.bin'&&e.unavailable&&!e.sessionId)));await fs.rm(mixedRepo,{recursive:true});await fs.rm(mixedLeft,{recursive:true});await fs.rm(mixedRight,{recursive:true});await openSessionFile(mixedArchive);await frame.locator('#review-groups button').last().click();await frame.locator('[data-path="asset.bin"]').click();await until(async()=>(await frame.locator('#message.error').textContent()).includes('Binary'));await frame.locator('[data-path="good.ts"]').click();await until(async()=>(await frame.locator('#right-info').textContent()).includes('Archived snapshot'));checks.push('Portable archive reopens mixed trees with missing sources, retains unavailable reasons and opens the captured text snapshot');
 const agentRoot=path.join(ready.fixtures.root,'agent-review');await fs.mkdir(path.join(agentRoot,'src'),{recursive:true});await fs.mkdir(path.join(agentRoot,'test'),{recursive:true});const agentFiles=['src/one.ts','src/two.ts','test/three.ts'];for(const file of agentFiles)await fs.writeFile(path.join(agentRoot,file),'const value = 1;\n');
 const agentOpen=file=>({left:{kind:'text',label:'Before '+file,text:'const value = 0;\n'},right:{kind:'file',uri:path.join(agentRoot,file)},title:file});
 const one=await request('/open',agentOpen(agentFiles[0]));const two=await request('/open',agentOpen(agentFiles[1]));assert.equal((await request('/open',agentOpen(agentFiles[0]))).id,one.id);await frame.locator(`[data-session-id="${one.id}"]`).click();await until(async()=>await frame.locator('#follow-agent-control').getAttribute('data-follow')==='false');const three=await request('/open',agentOpen(agentFiles[2]),false);await request('/edit',{id:two.id,side:'right',text:'const value = 3;\n',expectedHash:two.right.hash},false);await frame.locator(`[data-session-id="${three.id}"]`).waitFor();assert.equal(await frame.locator('#right-name').textContent(),path.join(agentRoot,agentFiles[0]));for(const id of [one.id,two.id,three.id])assert.equal(await frame.locator(`[data-session-id="${id}"]`).count(),1);await frame.locator(`[data-session-id="${two.id}"]`).click();await until(async()=>(await frame.locator('#right-name').textContent())===path.join(agentRoot,agentFiles[1]));await frame.locator(`[data-session-id="${one.id}"]`).click();await until(async()=>(await frame.locator('#right-name').textContent())===path.join(agentRoot,agentFiles[0]));checks.push('Agent files accumulate in Files independently of history; repeated opens retain IDs, users revisit every diff and selection pauses automatic switching during later agent edits');
 await select('layout','right');await click('add-comment');await frame.locator('.comment-input:visible').fill('Please change the value to 4');await frame.locator('.comment-submit:visible').click();let feedback;await until(async()=>{feedback=(await request('/comments?session='+one.id)).find(c=>c.body==='Please change the value to 4');return feedback;});let card=frame.locator(`[data-comment-id="${feedback.id}"]`);await card.getByRole('button',{name:'Reply',exact:true}).click();await frame.locator('.comment-input:visible').fill('Please preserve the variable name.');await frame.locator('.comment-submit:visible').click();await until(async()=>(await request('/comments?session='+one.id))[0].replies.length===1);await request('/reply',{id:one.id,commentId:feedback.id,body:'I will keep the name and change only the value.'});await until(async()=>(await card.locator('.comment-reply').allTextContents()).some(t=>t.includes('change only the value')));const latestOne=(await request('/sessions')).find(s=>s.id===one.id);await request('/edit',{id:one.id,side:'right',text:'const value = 4;\n',expectedHash:latestOne.right.hash});await request('/save',{id:one.id,side:'right'});await request('/resolve',{id:one.id,commentId:feedback.id,resolved:true});await card.getByRole('button',{name:'Reopen',exact:true}).waitFor();assert.equal(await fs.readFile(path.join(agentRoot,agentFiles[0]),'utf8'),'const value = 4;\n');await card.getByRole('button',{name:'Reopen',exact:true}).click();await until(async()=>(await request('/comments?session='+one.id))[0].resolved===false);await card.getByRole('button',{name:'Resolve',exact:true}).click();await until(async()=>(await request('/comments?session='+one.id))[0].resolved===true);checks.push('Users add/reply to comments; agents read feedback, reply inline, fix and resolve it; users can reopen or resolve threads');
 await click('copy-review');await until(async()=>(await frame.locator('#copy-review').textContent())==='Review request copied');await fs.rm(path.join(dir,'clipboard.txt'),{force:true});await fs.writeFile(path.join(dir,'read-clipboard'),'read');const reviewHandoff=await until(async()=>fs.readFile(path.join(dir,'clipboard.txt'),'utf8'));assert.ok(reviewHandoff.includes('Review request: Read `comments`'));assert.ok(reviewHandoff.includes('project REPO'));checks.push('Copy review request includes the live connection, updated skill and instructions to read/reply/fix unresolved comments');
 const project=await request('/project',{repo:ready.fixtures.repo,leftRef:'master',rightRef:'WORKING'});assert.ok(project.entries.some(e=>e.path==='app.ts'&&e.sessionId));await select('file-set',project.id);await until(async()=>await frame.locator('#file-count').textContent()===String(project.entries.length));await frame.locator('[data-path="app.ts"]').click();const agentGroup=(await request('/groups')).find(g=>g.label==='Agent files');await select('file-set',agentGroup.id);await frame.locator(`[data-session-id="${one.id}"]`).click();await until(async()=>(await frame.locator('#right-name').textContent())===path.join(agentRoot,agentFiles[0]));checks.push('Agent project command publishes the full changed-file hierarchy and File set switches between project and accumulated agent comparisons');
 const agentArchive=path.join(root,'artifacts','v050-agent-review.diff_studio');await fs.rm(agentArchive,{force:true});await saveSessionFile(agentArchive);await openSessionFile(agentArchive);const importedOne=(await request('/sessions')).find(s=>s.archived&&s.comments.some(c=>c.body==='Please change the value to 4'));assert.ok(importedOne);const importedGroup=(await request('/groups')).find(g=>g.label==='Agent files'&&g.entries.some(e=>e.sessionId===importedOne.id));assert.equal(await frame.locator('#file-set').inputValue(),importedGroup.id);await click('files-tab');await select('file-set',importedGroup.id);await frame.locator(`[data-session-id="${importedOne.id}"]`).click();await until(async()=>(await frame.locator('#right-info').textContent()).includes('Archived snapshot'));card=frame.locator(`[data-comment-id="${feedback.id}"]`);await card.getByRole('button',{name:'Reopen',exact:true}).waitFor();assert.equal(await card.locator('.comment-reply').count(),2);checks.push('Saved sessions restore the accumulated agent Files tree, text snapshots, user/agent replies and resolved comment state');


 }
 await page.screenshot({path:'artifacts/vscode-ui.png',fullPage:true});assert.deepEqual(failures,[]);
 const report={passed:true,checks,pageErrors:failures,date:new Date().toISOString()};await fs.writeFile('artifacts/vscode-test.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){if(browser)await browser.contexts()[0]?.pages()[0]?.screenshot({path:'artifacts/vscode-failure.png'}).catch(()=>{});console.error(e);await fs.writeFile('artifacts/vscode-test.json',JSON.stringify({passed:false,checks,error:e.message,pageErrors:failures},null,2));process.exitCode=1;}
finally{await fs.writeFile(path.join(dir,'finish'),'done');if(browser)await browser.close();await wait(1000);child.kill();await log.close();if(remoteFiles.length){await new Promise((resolve,reject)=>{const cleanup=spawn('ssh',['-T','-o','BatchMode=yes','-o','ConnectTimeout=15',process.env.DIFF_STUDIO_REMOTE_UI,'rm','-f','--',...remoteFiles],{stdio:'ignore'});cleanup.on('exit',code=>code===0?resolve():reject(new Error('Remote UI fixture cleanup failed')));cleanup.on('error',reject);});}}
